export const ROUND_TIME_SECONDS = 90;

export const suggestions = [
  "Apple",
  "Banana",
  "Carrot",
  "Dog",
  "Frog",
  "Giraffe",
  "House",
  "Ice cream",
  "Jellyfish",
  "Kite",
  "Lion",
  "Monkey",
  "Nest",
  "Octopus",
  "Pineapple",
  "Quail",
  "Rabbit",
  "Sun",
  "Tree",
  "Umbrella",
  "Violin",
  "Watermelon",
  "Xylophone",
  "Yak",
  "Zebra",
  "Airplane",
  "Boat",
  "Camera",
  "Dragonfly",
  "Ferris wheel",
  "Guitar",
  "House",
  "Igloo",
  "Jelly",
  "Kitten",
  "Lighthouse",
  "Moon",
  "Narwhal",
  "Ocean",
  "Panda",
  "Quilt",
  "Rainbow",
  "Sunflower",
  "Train",
  "Unicorn",
  "Zipper",
  "Angel",
  "Butterfly",
  "Cloud",
  "Daisy",
  "Egg",
  "Fire",
  "Grass",
  "Heart",
  "Ice",
  "Jar",
  "Key",
  "Leaf",
  "Mountains",
  "Night",
  "Owl",
  "Pinecone",
  "Quail",
  "Snowman",
  "Tree",
  "Van",
  "Water",
  "Yellow",
  "Zucchini",
  "Ant",
  "Bear",
  "Cat",
  "Duck",
  "Fish",
  "Horse",
  "Iguana",
  "Jaguar",
  "Kangaroo",
  "Lion",
  "Monkey",
  "Nest",
  "Otter",
  "Panda",
  "Quail",
  "Rabbit",
  "Snake",
  "Tiger",
  "Vulture",
  "Whale",
  "Yak",
  "Zebra",
  "Air balloon",
  "Balloon",
  "Camera",
  "Dolphin",
  "Earth",
  "Avalanche",
  "Blizzard",
  "Carnival",
  "Drought",
  "Eclipse",
  "Famine",
  "Glacier",
  "Hurricane",
  "Inferno",
  "Jungle",
  "Kangaroo",
  "Lightning",
  "Monsoon",
  "Nirvana",
  "Oasis",
  "Pirate",
  "Quicksand",
  "Rainforest",
  "Savannah",
  "Thunder",
  "UFO",
  "Volcano",
  "Waterfall",
  "Xenon",
  "Yellowstone",
  "Zoo",
  "Ballet",
  "Cactus",
  "Desert",
  "Elephant",
  "Flamingo",
  "Hammock",
  "Igloo",
  "Jellyfish",
  "Kite",
  "Lighthouse",
  "Mountain",
  "Nest",
  "Octopus",
  "Penguin",
  "Quilt",
  "Sunflower",
  "Tent",
  "Waterfall",
  "Yacht",
  "Zebra",
  "Astronaut",
  "Basketball",
  "Camping",
  "Diving",
  "Fireworks",
  "Gardening",
  "Hiking",
  "Ice skating",
  "Jogging",
  "Kayaking",
  "Lacrosse",
  "Motorcycle",
  "Ninja",
  "Origami",
  "Painting",
  "Quilting",
  "Rollerblading",
  "Skiing",
  "Tennis",
  "Frisbee",
  "Volleyball",
  "Wrestling",
  "Yoga",
  "Ziplining",
  "Aquarium",
  "Beach",
  "Cruise",
  "Dolphin",
  "Eiffel Tower",
  "Ferris wheel",
  "Gondola",
  "Hot air balloon",
  "Island",
  "Jet ski",
  "Kangaroo",
  "Lighthouse",
  "Museum",
  "National park",
  "Opera",
  "Parachuting",
  "Quayside",
  "Rodeo",
  "Statue of Liberty",
  "Theater",
  "Underwater",
  "Vineyard",
  "Water park",
  "Xenophobia",
  "Yellowstone",
  "Zoo",
]

export const names = [
  "Captain Crunch",
  "The Incredible Burrito",
  "Sir Jokes-a-Lot",
  "Mad Hatter",
  "Disco Queen",
  "Professor Purrfect",
  "Baron Von Tickles",
  "Count Quirkula",
  "Cheesy McSneeze",
  "Ninja Noodle",
  "The Baconator",
  "Lady Wafflecone",
  "Mr. Bumblebee",
  "Dr. Bubbles",
  "The Dancing Donut",
  "Commander Zucchini",
  "Sassy Pants",
  "Captain Cuddles",
  "Duke Doodle",
  "The Curly Mustache",
  "Sir Dizzy Doodle",
  "Madame Giggles",
  "General Bumblebee",
  "The Ticklish Tornado",
  "Lord Ticklesworth",
  "Miss Silliness",
  "Doctor Whimsy",
  "Colonel Cupcake",
  "The Jolly Jellybean",
  "Mr. Gigglesnort",
  "Lady Fluffington",
  "Sir Chuckleberry",
  "Princess Gigglepants",
  "The Laughing Llama",
  "Count Chuckles",
  "Doctor Quackster",
  "Captain Sillypants",
  "Lady Wobblebottom",
  "The Quirky Quokka",
  "Sir Snort-a-Lot",
  "Professor Wiggles",
  "Commander Guffaw",
  "Princess Tickleton",
  "Mr. Zany Zebra",
  "Madame Chucklebuns",
  "General Snickerdoodle",
  "The Hilarious Hippo",
  "Doctor Gigglegoose",
  "Baroness Guffawsalot",
  "Sir Wobbleberry",
  "Lady Snortington",
  "Captain Silliness",
  "The Chuckling Chameleon",
  "Miss Wigglesworth",
  "Duke Guffaw",
  "The Laughing Lizard",
  "Countess Gigglesnort",
  "Dr. Jokesalot",
  "Colonel Wobblepants",
  "The Whimsical Walrus",
  "Sir Gigglegoose",
  "Madame Wobblebottom",
  "General Chucklesworth",
  "Princess Snickerdoodle",
  "Mr. Zanyzebra",
  "Lady Chucklebuns",
  "Professor Snortington",
  "Commander Silliness",
  "The Giggling Gecko",
  "Miss Wigglesnort",
  "Duke Guffawington",
  "The Laughing Lemur",
  "Countess Gigglesalot",
  "Dr. Jokester",
  "Colonel Wobblesocks",
  "The Whimsical Warthog",
  "Sir Gigglesnort",
  "Madame Chucklebutt",
  "General Snickerpants",
  "Princess Ticklesworth",
  "Mr. Zanyleopard",
  "Lady Chucklebutt",
  "Professor Snickersnort",
  "Commander Sillinesskins",
  "The Giggling Gorilla",
  "Miss Wigglepants",
  "Duke Guffawsworth",
  "The Laughing Lion",
  "Countess Gigglesnicker",
  "Dr. Jokesworth",
  "Colonel Wobblefeet",
  "The Whimsical Weasel",
  "Sir Gigglesnicker",
  "Madame Chucklesocks",
  "General Snickerbottom",
  "Princess Ticklepants",
  "Mr. Zanypanda",
  "Lady Chucklesocks",
  "Professor Snickerfeet",
  "Commander Sillinessmuffin"
];

export const colors = [
  // Red Colors
  ['#fff5f5', '#7f1d1d'], // Red-50, Red-700
  // Orange Colors
  ['#fffaf0', '#78350f'], // Orange-50, Orange-700
  // Yellow Colors
  ['#fffff0', '#744210'], // Yellow-50, Yellow-700
  // Green Colors
  ['#f0fff4', '#22543d'], // Green-50, Green-700
  // Blue Colors
  ['#f0f9ff', '#1e3a8a'], // Blue-50, Blue-700
  // Indigo Colors
  ['#f0f5ff', '#1c3d6d'], // Indigo-50, Indigo-700
  // Purple Colors
  ['#f6f5ff', '#4c1d95'], // Purple-50, Purple-700
  // Pink Colors
  ['#fff5f7', '#852029'], // Pink-50, Pink-700
  // Red-Violet Colors
  ['#fdf4ff', '#7924c0'], // Red-Violet-50, Red-Violet-700
  // Amber Colors
  ['#fffbf0', '#8d2b0b'], // Amber-50, Amber-700
  // Lime Colors
  ['#f7ffeb', '#3c8605'], // Lime-50, Lime-700
  // Emerald Colors
  ['#ecfdf5', '#276749'], // Emerald-50, Emerald-700
  // Teal Colors
  ['#f0fdfa', '#0d3331'], // Teal-50, Teal-700
  // Cyan Colors
  ['#f0fdff', '#145e7a'], // Cyan-50, Cyan-700
  // Light-Blue Colors
  ['#f0f9ff', '#1e3a8a'], // Light-Blue-50, Light-Blue-700
  // Violet Colors
  ['#f5f3ff', '#4c1d95'], // Violet-50, Violet-700
  // Fuchsia Colors
  ['#fff4f9', '#852029'], // Fuchsia-50, Fuchsia-700
  // Rose Colors
  ['#fff2f9', '#902340'], // Rose-50, Rose-700
];